version: "3.9"

services:
  redis:
    container_name: 'redis'
    image: redis/redis-stack:latest
    volumes:
      - redis-volumes:/data
    ports:
      - 8001:8001
  server:
    container_name: 'redis-server'
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379

volumes:
  redis-volumes: